apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ descry_pvc_name }}"
  namespace: "{{ archivist_namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ descry_pvc_size }}
