apiVersion: v1
kind: Service
metadata:
  name: {{ appname }}-service
  namespace: archives
  annotations:
    metallb.universe.tf/address-pool: default-pool
spec:
  type: LoadBalancer
  selector:
    app: {{ appname }}
  ports:
    - port: {{ appport }}
      targetPort: {{ appport }}
  loadBalancerIP: 172.17.1.65
