---
apiVersion: v1
kind: Service
metadata:
  name: {{ sentinel_name }}
  namespace: {{ archives_namespace }}
spec:
  clusterIP: None
  ports:
  - port: 5000
    targetPort: 5000
    name: {{ sentinel_name }}
  selector:
    app: {{ sentinel_name }}
