apiVersion: v1
kind: Service
metadata:
  name: {{ descry_service_name }}
  namespace: {{ archivist_namespace }}
  annotations:
    metallb.universe.tf/address-pool: default-pool
spec:
  selector:
    app: {{ descry_label }}
  ports:
  - port: {{ descry_port }}
    targetPort: {{ descry_port }}
  type: LoadBalancer
  loadBalancerIP: {{ descry_service_ip }}
